name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
jobs:
  running-the-thing:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - uses: actions/checkout@v3
      - name: another actions file...
        uses: ./.github/someaction   
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "hi from ${RUNNER_NAME}" > ~/foo.txt && date >> ~/foo.txt
        if: runner.os != 'Windows'
      - name: Uploading build artfact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: artifact_name
          path: ~/foo.txt
          retention-days: 2

  downloading-the-artifact:
    needs: running-the-thing
    runs-on: ubuntu-latest
    steps:
      - name: Download that artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact_name
      - name: show the artifact
        shell: bash
        run: |
          contents=`cat foo.txt`
          echo "the contents of foo: ${contents}"

